#define TRUE 1
#define FALSE 0

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define FPS 30
#define DESIREDDELTA 1000/FPS

#define GRAVITY 0.5f

#define RIGHT 2
#define LEFT 3

#define TILE_WIDTH 96
#define TILE_HEIGHT 24

#define MAP_WIDTH WINDOW_WIDTH/TILE_WIDTH + 1
#define MAP_HEIGHT WINDOW_HEIGHT/TILE_HEIGHT
